# Generated by Django 4.2.6 on 2024-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
