# Generated by Django 4.2.6 on 2024-10-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
