# Generated by Django 4.2.6 on 2024-11-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_instance_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityzone',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabilityzone',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
