# Generated by Django 4.2.6 on 2024-10-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_itemdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
