# Generated by Django 4.2.6 on 2024-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_alter_availabilityzone_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
